import Head from "next/head";
import Navbar from "./components/Navbar/Navbar";
import Progress from "./components/progress/Progress";
import BootstrapCarousel from "./components/carousel/Bootstrap";
import ServicesMain from "./components/serviceMain/ServicesMain";
import Footer from "./components/Footer";
import Projets from "./components/proj-main/Projets";
import Blogs from "./components/Articles/Blogs";
import Titres from "./components/titres/titres";
import Partenariat from "./components/partenariat/partenariat";
import { Carousel } from "react-responsive-carousel";
const Home = () => {
  return (
    <>
      <Head>
        <title>Ecosolution</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/1-.png" />
      </Head>
      <main>
        <div>
          <Navbar />
          <div className="header-test">
            <Carousel showThumbs={false}>
            <div className="gallery hello">
                <img src="../assets/img09.jpg" height="500" width="250" />
                </div>
              <div className="gallery hello">
                <img src="../assets/IMG02.jpg" height="500" width="250" />
              </div>
              <div className="gallery hello">
                <img src="../assets/IMG04.jpg" height="500" width="250" />
              </div>
            </Carousel>
          </div>
          <div className="our_stats">
            <Progress />
          </div>
          <div className="parallax"></div>

          <div className="section1">
            <div className="section1_title">
              <h1>Decouvrir nos Services</h1>
            </div>
            <div>
              <ServicesMain />
            </div>
          </div>
          <div className="parallax"></div>

          <div className="section2">
            <div className="section2_title">
              <h1>Nos Projets référents</h1>
            </div>

            <Projets />
          </div>
          <div className="parallax"></div>

          <div className="section3">
            <div className="section3_title">
              <h1>
                Pour savoir plus sur l'énergie solaire vous pouvez lire ces
                articles
              </h1>
            </div>

            <Blogs />
          </div>

          <Partenariat />

          <Footer />          
  
        </div>
        <script
          src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js"
          integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe"
          crossOrigin="anonymous"
        ></script>
      </main>
    </>
  );
}

export default Home;
