import Head from "next/head";
import Navbar from "./components/Navbar/Navbar";
import Progress from "./components/progress/Progress";
import BootstrapCarousel from "./components/carousel/Bootstrap";
import ServicesMain from "./components/serviceMain/ServicesMain";
import Footer from "./components/Footer";
import Projets from "./components/proj-main/Projets";
import Blogs from "./components/Articles/Blogs";
import Titres from "./components/titres/titres";
import Partenariat from "./components/partenariat/partenariat";
import { Carousel } from "react-responsive-carousel";
export default function Home() {
  return (
    <>
      <Head>
        <title>Ecosolution</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>
          <Navbar />

          {/*

          <Progress/>
          <h2>
          <Titres text="Découvrir nos services"/>
          </h2>
         
          <ServicesMain />
          
          <h2>  <Titres text="Nos projets réferents"/></h2>
          <Projets />
         
          <h2> <Titres text="Pour savoir plus sur l'energie solaire vous pouvez lire ces articles"/></h2>
          <Blogs/>
          
          <h2><Titres text="NOS PARTENAIRES"/></h2> */}

          <div class="header-test">
            <Carousel showThumbs={false}>
              <div className="gallery hello">
                <img src="../assets/IMG01.jpg" height="500" width="250" />
              </div>
              <div className="gallery hello">
                <img src="../assets/IMG02.jpg" height="500" width="250" />
              </div>
              <div className="gallery hello">
                <img src="../assets/IMG04.jpg" height="500" width="250" />
              </div>
            </Carousel>
          </div>

          <div class="our_stats">
            <Progress />
          </div>
          <div class="parallax"></div>

          <div class="section1">
            <div class="section1_title">
              <h1>Decouvrir nos Services</h1>
            </div>
            <div>
              <ServicesMain />

              {/* <div class="service-item">
                <div class="img"></div>
                <h2>Karriery</h2>
                <p>
                  Lorem ipsum dolor sit amet, consectetur adipisicing elit.
                  Facere non aspernatur...
                </p>
              </div>
              <div class="service-item">
                <div class="img"></div>
                <h2>Karriery</h2>
                <p>
                  Lorem ipsum dolor sit amet, consectetur adipisicing elit.
                  Facere non aspernatur...
                </p>
              </div>
              <div class="service-item">
                <div class="img"></div>
                <h2>Karriery</h2>
                <p>
                  Lorem ipsum dolor sit amet, consectetur adipisicing elit.
                  Facere non aspernatur...
                </p>
              </div> */}
            </div>
          </div>
          <div class="parallax"></div>

          <div class="section2">
            <div class="section2_title">
              <h1>Nos Project referents</h1>
            </div>

            <Projets />
          </div>
          <div class="parallax"></div>

          <div class="section3">
            <div class="section3_title">
              <h1>
                Pour savoir plus sure l'energie solair vous pouvez lire ces
                articles
              </h1>
            </div>

            <Blogs />
          </div>

          <Partenariat />

          <Footer />
        </div>
        <script
          src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js"
          integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe"
          crossorigin="anonymous"
        ></script>
      </main>
    </>
  );
}
