import Head from 'next/head';

const Layout = ({ children }) => {
  return (
    <div>
     <Head>
        <title>Ecosolution</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/1-.png" />
      </Head>
      {children}
    </div>
  );
};

export default Layout;