import Head from "next/head";
// import styles from '../styles/Home.module.css'
import styles from "../styles/secondPageProjet.module.scss";
import { useEffect, useState } from "react";
import { useRouter } from "next/router";
import "react-responsive-carousel/lib/styles/carousel.min.css";
import Navbar from "./components/Navbar/Navbar";
import Footer from "./components/Footer";
import { Carousel } from "react-responsive-carousel";
import YouTube, { YouTubeProps } from "react-youtube";

const imgg1 = new URL("../../public/assets/IMG_blog1.jpg", import.meta.url);
export default function SecondPageProjet({ data }) {
  const router = useRouter();
  const PROTOCOL_AND_HOST_NAME_PART_OF_THE_URL = "https://www.ecosolution.tn/api/back";
  const [projet, setprojet] = useState([]);
  const Gallery = ({ imagePaths }) => {
    if (!Array.isArray(imagePaths)) {
      imagePaths = [imagePaths];
    }
    return (
      <div className="gallery">
        {imagePaths.map((path) => (
          <img
            key={path}
            src={`https://www.ecosolution.tn/api/back/imagesProjet/${path}`}
            alt={path}
          />
        ))}
      </div>
    );
  };

  useEffect(() => {
    fetch(`${PROTOCOL_AND_HOST_NAME_PART_OF_THE_URL}/projet/${data.id}`)
      .then((response) => response.json())
      .then((data) => {
        console.log("hedhi idata", data);
        setprojet(data);
      })
      .catch((error) => console.log(error));
  }, []);
  useEffect(() => {
    console.log("hedha projet", projet);
    console.log("hetha taille imta3 tableau images", projet?.images?.length);
  }, [projet]);
  const MyVideoComponent = () => {
    const videoId = "q9nAytDl0JA&list=RDq9nAytDl0JA&start_radio=1"; // Replace with your YouTube video ID
    const videoOptions = {
      height: "360",
      width: "640",
      playerVars: {
        autoplay: 1,
      },
    };
  };

  return (
    <div>
     <Head>
        <title>Ecosolution</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/1-.png" />
      </Head>
      <Navbar />
       <div className={styles.flex_container}>
         <div className={styles.project_info_container}>
        <div className={styles.basic_info}>
          <div className={styles.text_info}>
            <div>
              <h2>{projet.titre}</h2>
              <h4>Type : {projet.type}</h4>
              <h4>
                Production annuelle du projet : {projet.productionAnuelle} KWC
              </h4>
              <h4>Adresse : {projet.adresse}</h4>
            </div>
          </div>
          <div className={styles.carroussel}>
            <Carousel showThumbs={false}>
              {projet.images &&
                projet.images.map((image, index) => (
                  <div key={index}>
                    <Gallery imagePaths={projet.images[index]}></Gallery>
                  </div>
                ))}
            </Carousel>
          </div>
        </div>
        <div className={styles.more_detailed_info}>
             <div className={styles.project_video}>
               <div className={styles.vid}>
            <YouTube className={styles.vid} videoId={projet.video} />{" "}
            <div>{/* Render the YouTube video */}</div>
          </div>
          </div>
          <div className={styles.text_details}>
            <p>{projet.description}</p>
          </div>
       
          
        </div>
      </div>
       </div>

       <Footer />
    </div>
  );
}
SecondPageProjet.getInitialProps = async ({ query }) => {
  const data = query;

  return { data };
};